# Render.com Blueprint for toruabii.ee
# https://docs.render.com/blueprint-spec

services:
  - type: web
    runtime: node
    name: toruabii
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
